-- FluxCord Store database
-- Run this entire file once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  phone text default '',
  name text default '',
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.otps (
  email text primary key,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  price_bdt integer not null default 0 check (price_bdt >= 0),
  image text not null default '',
  tag text not null default 'FRESH' check (tag in ('FRESH', 'HOT', 'SPECIAL')),
  delivery text not null default 'Email delivery',
  file_url text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_code text unique,
  user_id bigint references public.users(id) on delete set null,
  email text not null,
  phone text not null default '',
  payment_method text not null,
  trxid text not null default '',
  subtotal integer not null default 0,
  discount integer not null default 0,
  total integer not null default 0,
  status text not null default 'PENDING' check (status in ('PENDING', 'PAID', 'DELIVERED', 'CANCELLED')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  name text not null,
  price integer not null default 0,
  quantity integer not null default 1
);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  type text not null default 'percent' check (type in ('percent', 'fixed')),
  value integer not null default 0,
  active boolean not null default true,
  uses integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  user_id bigint references public.users(id) on delete set null,
  product_id bigint not null references public.products(id) on delete cascade,
  email text not null,
  stars integer not null check (stars between 1 and 5),
  comment text not null default '',
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

-- Safe upgrades for an existing FluxCord database.
alter table public.reviews add column if not exists order_id bigint references public.orders(id) on delete cascade;
alter table public.reviews add column if not exists user_id bigint references public.users(id) on delete set null;
create unique index if not exists reviews_order_product_unique on public.reviews(order_id, product_id) where order_id is not null;

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  order_id bigint unique not null references public.orders(id) on delete cascade,
  email text not null,
  status text not null default 'OPEN' check (status in ('OPEN', 'CLOSED')),
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete cascade,
  sender text not null check (sender in ('USER', 'ADMIN')),
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value text not null
);

insert into public.settings(key, value) values
  ('store_name', 'FluxCord'),
  ('tagline', 'Premium digital knowledge, delivered with care.'),
  ('hero_title', 'Learn faster.\nBuild smarter.'),
  ('hero_description', 'Premium e-books for students, creators and digital entrepreneurs.'),
  ('stat_customer_bonus', '10'),
  ('stat_sold_bonus', '20'),
  ('discord', 'https://discord.com/'),
  ('facebook', 'https://facebook.com/'),
  ('email', 'support@fluxcord.store')
on conflict (key) do nothing;

insert into public.products(name, description, price_bdt, image, tag, delivery, file_url)
select * from (values
  ('Starter Guide', 'A clean starter e-book for learning digital skills.', 199, '', 'FRESH', 'Email delivery', ''),
  ('Creator Playbook', 'Practical systems for building a digital brand.', 399, '', 'HOT', 'Email delivery', ''),
  ('Ultimate Bundle', 'A complete bundle of FluxCord guides and resources.', 799, '', 'SPECIAL', 'Email delivery', '')
) as seed(name, description, price_bdt, image, tag, delivery, file_url)
where not exists (select 1 from public.products);

-- The application uses the service-role key on the server.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY in frontend code.
